blank_issues_enabled: false
contact_links:
  - name: 🚫 No support for Refined Storage v1.x
    url: https://refinedmods.com/refined-storage/need-help.html#_supported_versions
    about: Refined Storage v1.x is no longer maintained. We do not accept issues or provide support for it.
  - name: 👥 Discord Community Support
    url: https://discordapp.com/invite/VYzsydb
    about: Please ask and answer questions here. Issues should be used for bugs and feature requests for Refined Storage v2.x.
