= Processing recipes

In xref:getting-started-with-autocrafting.adoc[], you learned how to automate regular crafting recipes.

But what if you want to automate tasks that don't use a crafting grid - like smelting iron ore into ingots?
For this, you use xref:../autocrafting/pattern.adoc#_processing_patterns[processing patterns].

== Creating processing patterns

Use the xref:../autocrafting/pattern-grid.adoc[] in processing mode to create a xref:../autocrafting/pattern.adoc#_processing_patterns[processing pattern].
The interface allows defining up to 9 inputs and 9 expected outputs:

- **Inputs** – Resources pulled from the storage network and inserted into the machine.
- **Outputs** – Resources expected back in the storage network after processing.

== Example

To automate the conversion of
link:https://minecraft.gamepedia.com/Iron_Ore[Iron Ore] → link:https://minecraft.gamepedia.com/Iron_Ingot[Iron Ingot]:

- Set **1 Iron Ore** as the input.
- Set **1 Iron Ingot** as the output.

=== Alternatives

For each input, you can define allowed alternatives using link:https://minecraft.gamepedia.com/Tag[Minecraft's tag system].

== Using the pattern

1. Place a xref:../autocrafting/autocrafter.adoc[] facing the machine correctly (e.g., furnace) so it can insert inputs into the correct slot.
2. Insert the xref:../autocrafting/pattern.adoc#_processing_patterns[processing pattern] into the autocrafter.
3. When requested, the autocrafter will insert the inputs into the machine.

You must ensure the output is returned to the storage network - this is how the storage network knows that the task can be completed.

Use a device like:

- xref:../input-and-output/interface.adoc[]
- xref:../input-and-output/importer.adoc[]

== Chaining autocrafters

You can xref:../autocrafting/autocrafter.adoc#_chaining[chain multiple autocrafters] to a single machine to handle more patterns for a single machine.
