= Regulator Upgrade
:icon: regulator-upgrade.png
:from: v1.8.3-beta

The {doctitle} is an upgrade for the xref:../input-and-output/exporter.adoc[] and xref:../input-and-output/importer.adoc[] that maintains a set amount of resources in the connected inventory.

== Configuration

Before inserting the {doctitle} into a device, configure the resource and amount to be stocked by using the {doctitle} in your hand.

== Usage in an Exporter

When used in an xref:../input-and-output/exporter.adoc[], the {doctitle} ensures the connected inventory does not exceed the specified amount, only inserting more when necessary.

=== Autocrafting

When combined with a xref:autocrafting-upgrade.adoc[], the {doctitle} can trigger autocrafting if the storage network runs out of stock.

== Usage in an Importer

When used in an xref:../input-and-output/importer.adoc[], the {doctitle} ensures the connected inventory does not drop below the specified amount, only extracting excess resources.

== Applicable storage network devices

- xref:../input-and-output/importer.adoc[] (4)
- xref:../input-and-output/exporter.adoc[] (4)
