= Exporter
:icon: exporter.png
:from: v0.3.0-alpha

The {doctitle} extracts resources from the storage network and inserts them into a connected external inventory.

> Ensure that the {doctitle} is connected to the external inventory from the correct side, so it can access the desired slots for exporting.

== Filter

In the top row of the {doctitle}, specify which resources should be exported. If no resources are set, the {doctitle} will not function.

The last known state for each filtered resource is displayed:

- **None** – The resource was exported successfully or hasn't been exported yet.
- **Destination does not accept** – The external inventory rejected the resource.
- **Resource missing** – The resource is not available in the storage network.
- **Autocrafting started** – An autocrafting task was started for the missing resource (requires a xref:../upgrades/autocrafting-upgrade.adoc[]).
- **Autocrafting detected missing resources** – The autocrafting task could not start due to missing ingredients.

=== Fuzzy mode

Fuzzy mode, off by default, determines whether the filter considers additional attributes, such as a pickaxe's damage value.

== Scheduling mode

If multiple resources are set, the {doctitle} follows a scheduling mode to determine exporting order.

=== Default

Exports each resource in order, moving to the next only if the current one is unavailable.

=== Round-robin

Exports each resource in turn.

=== Random

Exports a random resource from the filter.

== Applicable upgrades

- xref:../upgrades/speed-upgrade.adoc[] (4)
* Increases transfer speed.
- xref:../upgrades/stack-upgrade.adoc[] (1)
* Increases transfer amount per tick.
- xref:../upgrades/autocrafting-upgrade.adoc[] (1)
* Starts an autocrafting task if the exported resource is missing and space is available in the connected inventory.
- xref:../upgrades/regulator-upgrade.adoc[] (4)
* Maintains a maximum amount of a resource in the connected inventory.

include::../../partials/connections.adoc[]

include::../../partials/redstone-mode.adoc[]

