name: Check changelog
on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review, labeled, unlabeled ]
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: dangoslen/changelog-enforcer@v3
        with:
          skipLabels: 'skip-changelog'