name: 'Unsupported versions'
on:
    issues:
        types: [ labeled, unlabeled, reopened ]
jobs:
    support:
        runs-on: ubuntu-latest
        steps:
            -   uses: dessant/support-requests@v3
                with:
                    github-token: ${{ github.token }}
                    support-label: 'unsupported'
                    issue-comment: >
                        :wave: @{issue-author}, we no longer support this version of Refined Storage.
                    close-issue: true
                    lock-issue: false
